name: Pyre

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Pyre Action
        uses: facebook/pyre-action@v0.0.2
        with:
            repo-directory: './dlss_updater/'
            requirements-path: '../requirements.txt'
