name: Winget Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  winget:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get release info
      id: release_info
      run: |
        $latest_release = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
        $version = $latest_release.tag_name -replace '^[vV]', ''
        $zipUrl = "https://github.com/${{ github.repository }}/releases/download/$($latest_release.tag_name)/DLSS.Updater.$version.zip"
        
        # Download ZIP to calculate hash
        Invoke-WebRequest -Uri $zipUrl -OutFile "DLSS.Updater.zip"
        $hash = (Get-FileHash -Path "DLSS.Updater.zip" -Algorithm SHA256).Hash
        
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "URL=$zipUrl" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "HASH=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh
    
    - name: Create manifest files
      id: create_manifests
      run: |
        $version = "${{ steps.release_info.outputs.VERSION }}"
        
        # Create simpler directory structure in current directory
        $manifestDir = "$version"
        New-Item -Path $manifestDir -ItemType Directory -Force
        
        # Create version manifest without leading spaces
        $versionContent = @"
PackageIdentifier: Recol.DLSSUpdater
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
"@
        
        $versionContent | Out-File -FilePath "$manifestDir\Recol.DLSSUpdater.yaml" -Encoding UTF8
        
        # Create installer manifest
        $installerContent = @"
PackageIdentifier: Recol.DLSSUpdater
PackageVersion: $version
MinimumOSVersion: 10.0.0.0
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: DLSS_Updater\DLSS_Updater.exe
    PortableCommandAlias: dlss-updater
  InstallerUrl: ${{ steps.release_info.outputs.URL }}
  InstallerSha256: ${{ steps.release_info.outputs.HASH }}
ManifestType: installer
ManifestVersion: 1.6.0
"@
        
        $installerContent | Out-File -FilePath "$manifestDir\Recol.DLSSUpdater.installer.yaml" -Encoding UTF8
        
        # Create locale manifest
        $localeContent = @"
PackageIdentifier: Recol.DLSSUpdater
PackageVersion: $version
PackageLocale: en-US
Publisher: Recol
PublisherUrl: https://github.com/Recol
Author: Deco
PackageName: DLSS Updater
PackageUrl: https://github.com/Recol/DLSS-Updater
License: AGPL-3.0
LicenseUrl: https://github.com/Recol/DLSS-Updater/blob/main/LICENSE
ShortDescription: A tool to update DLSS/XeSS DLLs for various games
Description: DLSS Updater is a utility that automatically updates DLSS, XeSS, and DirectStorage DLLs for games across multiple platforms.
Tags:
- dlss
- nvidia
- gaming
- xess
ManifestType: defaultLocale
ManifestVersion: 1.6.0
"@
        
        $localeContent | Out-File -FilePath "$manifestDir\Recol.DLSSUpdater.locale.en-US.yaml" -Encoding UTF8
        
        # List contents to verify
        Get-ChildItem $manifestDir
        
        # Output the manifest directory for next step
        echo "MANIFEST_DIR=$manifestDir" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh
    
    - name: Submit manifests
      run: |
        # Download wingetcreate for submission
        Invoke-WebRequest -Uri "https://github.com/microsoft/winget-create/releases/latest/download/wingetcreate.exe" -OutFile "wingetcreate.exe"
        
        # Submit the specific manifest directory
        .\wingetcreate.exe submit "${{ steps.create_manifests.outputs.MANIFEST_DIR }}" `
          --token "${{ secrets.WINGET_TOKEN }}"
      shell: pwsh
