name: Winget Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  winget:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get release info
      id: release_info
      run: |
        $latest_release = Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/releases/latest"
        $version = $latest_release.tag_name -replace '^[vV]', ''
        $zipUrl = "https://github.com/${{ github.repository }}/releases/download/$($latest_release.tag_name)/DLSS.Updater.$version.zip"
        
        # Download ZIP to calculate hash
        Invoke-WebRequest -Uri $zipUrl -OutFile "DLSS.Updater.zip"
        $hash = (Get-FileHash -Path "DLSS.Updater.zip" -Algorithm SHA256).Hash
        
        # Extract ZIP to check actual structure
        Expand-Archive -Path "DLSS.Updater.zip" -DestinationPath "extracted" -Force
        Write-Host "Extracted contents:"
        Get-ChildItem -Path "extracted" -Recurse | ForEach-Object { Write-Host $_.FullName }
        
        # Find the actual path to DLSS_Updater.exe
        $exePath = Get-ChildItem -Path "extracted" -Filter "DLSS_Updater.exe" -Recurse | Select-Object -First 1
        if ($exePath) {
            $relativePath = $exePath.FullName.Replace("$PWD\extracted\", "").Replace("\", "/")
            Write-Host "Found exe at: $relativePath"
            echo "RELATIVE_EXE_PATH=$relativePath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        } else {
            Write-Error "DLSS_Updater.exe not found in ZIP"
            exit 1
        }
        
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "URL=$zipUrl" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        echo "HASH=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh
    
    - name: Check for existing PR
      id: check_pr
      run: |
        $headers = @{
            "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
            "Accept" = "application/vnd.github.v3+json"
        }
        
        # Search for PRs
        $searchUrl = "https://api.github.com/search/issues?q=repo:microsoft/winget-pkgs+is:pr+is:open+Recol.DLSSUpdater"
        Write-Host "Searching for PRs at: $searchUrl"
        
        try {
            $response = Invoke-RestMethod -Uri $searchUrl -Headers $headers -Method Get
            Write-Host "Search response count: $($response.total_count)"
            
            if ($response.total_count -gt 0) {
                $pr = $response.items | Select-Object -First 1
                Write-Host "Found PR #$($pr.number): $($pr.title)"
                echo "PR_NUMBER=$($pr.number)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                echo "HAS_PR=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                
                # Get the PR details to find the branch name
                $prDetailsUrl = "https://api.github.com/repos/microsoft/winget-pkgs/pulls/$($pr.number)"
                $prDetails = Invoke-RestMethod -Uri $prDetailsUrl -Headers $headers -Method Get
                $branchName = $prDetails.head.ref
                echo "PR_BRANCH=$branchName" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            } else {
                Write-Host "No existing PR found"
                echo "HAS_PR=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            }
        } catch {
            Write-Host "Error searching for PRs: $_"
            echo "HAS_PR=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        }
      shell: pwsh
    
    - name: Update existing PR
      if: steps.check_pr.outputs.HAS_PR == 'true'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version = "${{ steps.release_info.outputs.VERSION }}"
        $exePath = "${{ steps.release_info.outputs.RELATIVE_EXE_PATH }}"
        $prNumber = "${{ steps.check_pr.outputs.PR_NUMBER }}"
        
        # Get PR details to find the correct fork
        $headers = @{
            "Authorization" = "Bearer ${{ secrets.GITHUB_TOKEN }}"
            "Accept" = "application/vnd.github.v3+json"
        }
        
        $prDetailsUrl = "https://api.github.com/repos/microsoft/winget-pkgs/pulls/$prNumber"
        $prDetails = Invoke-RestMethod -Uri $prDetailsUrl -Headers $headers -Method Get
        
        # Get the fork URL and branch name
        $forkCloneUrl = $prDetails.head.repo.clone_url
        $prBranch = $prDetails.head.ref
        $forkOwner = $prDetails.head.repo.owner.login
        
        Write-Host "Cloning from fork: $forkCloneUrl"
        Write-Host "Branch name: $prBranch"
        Write-Host "Fork owner: $forkOwner"
        
        # Configure git
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Clone the correct fork with authentication
        $authenticatedUrl = $forkCloneUrl -replace 'https://', "https://${{ secrets.WINGET_TOKEN }}@"
        git clone $authenticatedUrl winget-pkgs
        cd winget-pkgs
        git checkout $prBranch
        
        # Create directory structure
        $manifestDir = "manifests\r\Recol\DLSSUpdater\$version"
        New-Item -Path $manifestDir -ItemType Directory -Force
    
        
        # Create version manifest
        $versionContent = "PackageIdentifier: Recol.DLSSUpdater`n"
        $versionContent += "PackageVersion: $version`n"
        $versionContent += "DefaultLocale: en-US`n"
        $versionContent += "ManifestType: version`n"
        $versionContent += "ManifestVersion: 1.6.0"
        
        $versionPath = Join-Path $manifestDir "Recol.DLSSUpdater.yaml"
        $versionContent | Out-File -FilePath $versionPath -Encoding UTF8
        
        # Create installer manifest
        $installerContent = "PackageIdentifier: Recol.DLSSUpdater`n"
        $installerContent += "PackageVersion: $version`n"
        $installerContent += "MinimumOSVersion: 10.0.0.0`n"
        $installerContent += "Platform:`n"
        $installerContent += "- Windows.Desktop`n"
        $installerContent += "InstallModes:`n"
        $installerContent += "- interactive`n"
        $installerContent += "- silent`n"
        $installerContent += "Installers:`n"
        $installerContent += "- Architecture: x64`n"
        $installerContent += "  InstallerType: zip`n"
        $installerContent += "  InstallerUrl: ${{ steps.release_info.outputs.URL }}`n"
        $installerContent += "  InstallerSha256: ${{ steps.release_info.outputs.HASH }}`n"
        $installerContent += "  NestedInstallerType: portable`n"
        $installerContent += "  NestedInstallerFiles:`n"
        $installerContent += "  - RelativeFilePath: $exePath`n"
        $installerContent += "    PortableCommandAlias: dlss-updater`n"
        $installerContent += "  Scope: user`n"
        $installerContent += "  UpgradeBehavior: install`n"
        $installerContent += "ManifestType: installer`n"
        $installerContent += "ManifestVersion: 1.6.0"
        
        $installerPath = Join-Path $manifestDir "Recol.DLSSUpdater.installer.yaml"
        $installerContent | Out-File -FilePath $installerPath -Encoding UTF8
        
        # Create locale manifest
        $localeContent = "PackageIdentifier: Recol.DLSSUpdater`n"
        $localeContent += "PackageVersion: $version`n"
        $localeContent += "PackageLocale: en-US`n"
        $localeContent += "Publisher: Recol`n"
        $localeContent += "PublisherUrl: https://github.com/Recol`n"
        $localeContent += "PublisherSupportUrl: https://github.com/Recol/DLSS-Updater/issues`n"
        $localeContent += "Author: Deco`n"
        $localeContent += "PackageName: DLSS Updater`n"
        $localeContent += "PackageUrl: https://github.com/Recol/DLSS-Updater`n"
        $localeContent += "License: AGPL-3.0`n"
        $localeContent += "LicenseUrl: https://github.com/Recol/DLSS-Updater/blob/main/LICENSE`n"
        $localeContent += "ShortDescription: A tool to update DLSS, XeSS, and DirectStorage DLLs for various games`n"
        $localeContent += "Description: |`n"
        $localeContent += "  DLSS Updater is a utility that automatically updates DLSS (Deep Learning Super Sampling), XeSS (Intel Xe Super Sampling), and DirectStorage DLLs for games across multiple platforms.`n"
        $localeContent += "  `n"
        $localeContent += "  Note: This application requires administrative privileges to modify game files.`n"
        $localeContent += "Tags:`n"
        $localeContent += "- dlss`n"
        $localeContent += "- nvidia`n"
        $localeContent += "- gaming`n"
        $localeContent += "- xess`n"
        $localeContent += "- directstorage`n"
        $localeContent += "ReleaseNotes: https://github.com/Recol/DLSS-Updater/releases/tag/v$version`n"
        $localeContent += "ReleaseNotesUrl: https://github.com/Recol/DLSS-Updater/releases/tag/v$version`n"
        $localeContent += "ManifestType: defaultLocale`n"
        $localeContent += "ManifestVersion: 1.6.0"
        
        $localePath = Join-Path $manifestDir "Recol.DLSSUpdater.locale.en-US.yaml"
        $localeContent | Out-File -FilePath $localePath -Encoding UTF8
        
        # Commit and push changes
        git add .
        git commit -m "Update Recol.DLSSUpdater to version $version"
        git push origin $prBranch
      shell: pwsh
    
    - name: Create new PR
      if: steps.check_pr.outputs.HAS_PR == 'false'
      run: |
        $version = "${{ steps.release_info.outputs.VERSION }}"
        $exePath = "${{ steps.release_info.outputs.RELATIVE_EXE_PATH }}"
        
        # Create a temporary directory for manifests
        $tempDir = New-Item -ItemType Directory -Path "temp_manifests" -Force
        
        # Create version manifest
        $versionContent = "PackageIdentifier: Recol.DLSSUpdater`n"
        $versionContent += "PackageVersion: $version`n"
        $versionContent += "DefaultLocale: en-US`n"
        $versionContent += "ManifestType: version`n"
        $versionContent += "ManifestVersion: 1.6.0"
        
        $versionPath = Join-Path $tempDir "Recol.DLSSUpdater.yaml"
        $versionContent | Out-File -FilePath $versionPath -Encoding UTF8
        
        # Create installer manifest (same as above)
        # Create locale manifest (same as above)
        
        # Download wingetcreate
        $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/microsoft/winget-create/releases/latest"
        $asset = $latestRelease.assets | Where-Object { $_.name -eq "wingetcreate.exe" } | Select-Object -First 1
        Invoke-WebRequest -Uri $asset.browser_download_url -OutFile "wingetcreate.exe"
        
        # Use 'new' command for initial submission
        cd $tempDir
        ..\wingetcreate.exe new `
            --id Recol.DLSSUpdater `
            --version "$version" `
            --import . `
            --token "${{ secrets.WINGET_TOKEN }}" `
            --submit
      shell: pwsh
