- name: Download WingetCreate (Alternative)
      run: |
        # Use direct GitHub release URL instead of aka.ms redirect
        $releaseUrl = "https://api.github.com/repos/microsoft/winget-create/releases/latest"
        $release = Invoke-RestMethod -Uri $releaseUrl
        
        # Find the wingetcreate.exe asset
        $asset = $release.assets | Where-Object { $_.name -eq "wingetcreate.exe" }
        
        if ($asset) {
          Write-Host "Downloading from: $($asset.browser_download_url)"
          Invoke-WebRequest -Uri $asset.browser_download_url -OutFile "wingetcreate.exe"
          
          # Verify download
          $fileInfo = Get-Item "wingetcreate.exe"
          Write-Host "Downloaded: $($fileInfo.Name), Size: $($fileInfo.Length) bytes"
        } else {
          Write-Error "Could not find wingetcreate.exe in latest release"
          exit 1
        }
      shell: pwsh
